routes.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, session, flash
from sqlalchemy.exc import SQLAlchemyError
from passlib.handlers.pbkdf2 import pbkdf2_sha256

from form import AnggotaForm, BarangForm, BrgMasukForm, BrgOutForm, LoginForm
from models import AnggotaModel, BarangModel, BrgMasukModel, BrgOutModel, UserModel
from models import mysql

pages = Blueprint('pages', __name__, template_folder="templates", static_folder="static")

@pages.get('/')
@pages.route("/<_id>", methods=["GET", "POST"])
def index(_id=None):
    
    if session.get("id_user") is None:
        return redirect(url_for('.login'))
    
    getMsk = BrgMasukModel.get_all()
    getOut = BrgOutModel.get_all()
    
    total1 = sum(entry.qty for entry in getMsk)
    total2 = sum(entry.qty for entry in getOut)
    
    harga1 = sum(entry.harga_beli * entry.qty for entry in getMsk)
    harga2 = sum(entry.harga_jual * entry.qty for entry in getOut)
    
    return render_template( 'index.html',  side = 'Home', t1=total1, t2=total2, h1=harga1, h2=harga2 )

# login
@pages.route("/login", methods=['GET', 'POST'])
def login():
    if session.get("username"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = UserModel.get_user(form.username.data)

        if not user_data:
            flash("Login credentials not correct", category="error")
            return redirect(url_for(".login"))
    
        if user_data and pbkdf2_sha256.verify(form.password.data, user_data.password):
            session["id_user"] = user_data.id_user
            session["username"] = user_data.username
            session["jabatan"] = user_data.jabatan

            return redirect(url_for(".index"))

        flash("Login credentials not correct", "error")

    return render_template("login.html", form=form, side= 'Login' )


# logout
@pages.get("/logout")
def logout():
    session.clear()
    return redirect(url_for(".login"))


# regis
@pages.route("/registration", methods=["GET","POST"])
def reg():
    
    get_all_user = UserModel.get_all()
    form = LoginForm()
    
    if form.validate_on_submit():
        try:
            password = pbkdf2_sha256.encrypt(form.password.data)
            new_data = UserModel (form.username.data, form.password.data, form.jabatan.data)
            mysql.session.add(new_data)
            mysql.session.commit()
            
            return redirect(url_for('.login'))
        except SQLAlchemyError as ex:
            print(ex)
            mysql.session.rollback()
            
    return render_template("reg.html", form=form, data=get_all_user)



#  Fungsi untuk menampilkan Tabel Anggota
@pages.route("/anggota", methods=["GET","POST"])
def anggota():
    get_all_data = AnggotaModel.get_all()
    form = AnggotaForm()
    
    if form.validate_on_submit():
        if get_all_data:
            for i in get_all_data:
                if i.kode_anggota == form.kode_anggota.data:

                    return jsonify({'message': 'Kode Anggota Sudah Dipakai'}), 400        
        try:
            new_data = AnggotaModel(form.kode_anggota.data, form.nama_anggota.data, form.status.data, form.nik.data, form.bidang.data, form.keterangan.data)
            mysql.session.add(new_data)
            mysql.session.commit()
            
            return redirect(url_for('.anggota'))
        except SQLAlchemyError as ex:
            print(ex)
            mysql.session.rollback()
    
    return render_template("anggota.html", side = 'Anggota', form=form, data=get_all_data)


# Delete anggota
@pages.get("/anggota")
@pages.route("/anggota/<_id>", methods=['GET','POST'])
def deleteAnggota(_id=None):
    get_data_anggota = AnggotaModel.get_all()
    if _id is not None:
        deleteAnggota = AnggotaModel.get_by_id(_id)
        mysql.session.delete(deleteAnggota)
        mysql.session.commit()
        
        return redirect(url_for(".anggota"))

    return render_template("anggota.html", data=get_data_anggota)


# Edit Anggota
@pages.route('/anggota/edit/<_id>', methods=['GET', 'POST'] )
def editAnggota(_id):
    form = AnggotaForm()
    get_anggota_id = AnggotaModel.get_by_id(_id)
    if form.validate_on_submit():
        try:
            if form.kode_anggota.data != get_anggota_id.kode_anggota and form.kode_anggota.data is not None: get_anggota_id.kode_anggota = form.kode_anggota.data
            if form.nama_anggota.data != get_anggota_id.nama_anggota and form.nama_anggota.data is not None: get_anggota_id.nama_anggota = form.nama_anggota.data
            if form.status.data != get_anggota_id.status and form.status.data is not None: get_anggota_id.status = form.status.data
            if form.nik.data != get_anggota_id.nik and form.nik.data is not None: get_anggota_id.nik = form.nik.data
            if form.bidang.data != get_anggota_id.bidang and form.bidang.data is not None: get_anggota_id.bidang = form.bidang.data
            if form.keterangan.data != get_anggota_id.keterangan and form.keterangan.data is not None: get_anggota_id.keterangan = form.keterangan.data

            mysql.session.commit()
            
            return redirect(url_for('.anggota'))
        except SQLAlchemyError as x:
            print(x)
            mysql.session.rollback()
    return render_template("edit/edit-anggota.html", data=get_anggota_id, form=form)


# Tabel barang
@pages.route('/barang', methods=["GET","POST"])
def barang():
    get_all_data = BarangModel.get_all()
    form = BarangForm()
    
    if form.validate_on_submit():
        if get_all_data:
            try:
                new_data = BarangModel(form.nama_barang.data, form.satuan.data, form.harga_beli.data, form.harga_jual.data, form.stok_awal.data, form.keterangan.data)
                mysql.session.add(new_data)
                mysql.session.commit()
                
                return redirect(url_for('.barang'))
            except SQLAlchemyError as ex:
                print(ex)
                mysql.session.rollback()
            
    return render_template("barang.html", side="Barang", form=form, data=get_all_data)


# Edit barang
@pages.route('/barang/edit/<_id>', methods=['GET','POST'])
def editBarang(_id):
    get_barang_id = BarangModel.get_by_id(_id)
    form = BarangForm()
    
    if form.validate_on_submit():
        try:
            if form.nama_barang.data != get_barang_id.nama_barang and form.nama_barang.data is not None:
                get_barang_id.nama_barang = form.nama_barang.data
            if form.satuan.data != get_barang_id.satuan and form.satuan.data is not None:
                get_barang_id.satuan = form.satuan.data
            if form.harga_beli.data != get_barang_id.harga_beli and form.harga_beli.data is not None:
                get_barang_id.harga_beli = form.harga_beli.data
            if form.harga_jual.data != get_barang_id.harga_jual and form.harga_jual.data is not None:
                get_barang_id.harga_jual = form.harga_jual.data
            if form.stok_awal.data != get_barang_id.stok_awal and form.stok_awal.data is not None:
                get_barang_id.stok_awal = form.stok_awal.data
            if form.keterangan.data != get_barang_id.keterangan and form.keterangan.data is not None:
                get_barang_id.keterangan = form.keterangan.data

            mysql.session.commit()
            
            return redirect(url_for('.barang'))
        except SQLAlchemyError as x:
            print(x)
            mysql.session.rollback()
            
    return render_template("edit/edit-barang.html", side="Barang", form=form, data=get_barang_id)


# Delete barang
@pages.get("/barang")
@pages.route("/barang/<_id>", methods=['GET','POST'])
def deleteBarang(_id=None):
    get_data_barang = BarangModel.get_all()
    if _id is not None:
        deleteBarang = BarangModel.get_by_id(_id)
        mysql.session.delete(deleteBarang)
        mysql.session.commit()
        
        return redirect(url_for(".barang"))

    return render_template("barang.html", data=get_data_barang)


# tabel barang masuk
@pages.route("/barang/masuk", methods=["GET","POST"])
def barang_masuk():
    get_all_data = BrgMasukModel.get_all()
    form = BrgMasukForm()
    
    if form.validate_on_submit():
        if get_all_data:
            try:
                new_data = BrgMasukModel(form.tanggal_masuk.data, form.nama_barang.data, form.satuan.data, form.qty.data, form.harga_beli.data, form.distributor.data, form.keterangan.data)
                mysql.session.add(new_data)
                mysql.session.commit()
                
                return redirect(url_for('.barang_masuk'))
            except SQLAlchemyError as ex:
                print(ex)
                mysql.session.rollback()
                
    return render_template("barang-masuk.html", side ="Barang Masuk", data=get_all_data, form=form)


# edit brg masuk
@pages.route('/barang/masuk/edit/<_id>',methods=['GET','POST'] )  
def editBrgMasuk (_id):
    get_brgMasuk_id = BrgMasukModel.get_by_id(_id)
    form = BrgMasukForm()
    
    if form.validate_on_submit():
        try:
            if form.tanggal_masuk.data != get_brgMasuk_id.tanggal_masuk and form.tanggal_masuk.data is not None:
                get_brgMasuk_id.tanggal_masuk = form.tanggal_masuk.data
            if form.nama_barang.data != get_brgMasuk_id.nama_barang and form.nama_barang.data is not None:
                get_brgMasuk_id.nama_barang = form.nama_barang.data
            if form.satuan.data != get_brgMasuk_id.satuan and form.satuan.data is not None:
                get_brgMasuk_id.satuan = form.satuan.data
            if form.qty.data != get_brgMasuk_id.qty and form.qty.data is not None:

templates/macros/head.html
{% macro head() %}
<head>
  <meta charset="utf-8" />
  <title>{{side}}</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta content="" name="keywords" />
  <meta content="" name="description" />

  <!-- Favicon -->
  <link href="img/favicon.ico" rel="icon" />

  <!-- Google Web Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
    rel="stylesheet" />

  <!-- Sertakan SweetAlert2 CSS -->
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" />

  <!-- Icon Font Stylesheet -->
  <link
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
    rel="stylesheet" />
  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
    rel="stylesheet" />

  <!-- Libraries Stylesheet -->
  <link
    href="{{url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css')}}"
    rel="stylesheet" />
  <link
    href="{{url_for('static', filename='lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css')}}"
    rel="stylesheet" />

  <!-- Customized Bootstrap Stylesheet -->
  <link
    href="{{url_for('static', filename='css/bootstrap.min.css')}}"
    rel="stylesheet" />

  <!-- Template Stylesheet -->
  <link
    href="{{url_for('static', filename='css/style.css')}}"
    rel="stylesheet" />
</head>

{% endmacro %}

templates/macros/js.html
{%macro js()%}<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{{url_for('static', filename='lib/chart/chart.min.js')}}"></script>
<script src="{{url_for('static', filename='lib/easing/easing.min.js')}}"></script>
<script src="{{url_for('static', filename='lib/waypoints/waypoints.min.js')}}"></script>
<script src="{{url_for('static', filename='lib/owlcarousel/owl.carousel.min.js')}}"></script>
<script src="{{url_for('static', filename='lib/tempusdominus/js/moment.min.js')}}"></script>
<script src="{{url_for('static', filename='lib/tempusdominus/js/moment-timezone.min.js')}}"></script>
<script src="{{url_for('static', filename='lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js')}}"></script>

<!-- Template Javascript -->
<script src="{{url_for('static', filename='js/main.js')}}"></script>

<!-- Sertakan SweetAlert2 JS -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
  // Jika kode anggota sudah dipakai, tampilkan SweetAlert2
  {% if kode %}
  Swal.fire({
      icon: 'error',
      title: 'Kode Anggota Sudah Dipakai',
      text: 'Mohon masukkan kode anggota yang berbeda.',
      showConfirmButton: false,
      timer: 1500 // Waktu penundaan sebelum menutup alert (dalam milidetik)
  });
  {% endif %}
</script>

{%endmacro%}

templates/macros/main-layout.html
{% from "macros/head.html" import head %} {% from "macros/spinner.html" import
spinner %} {% from "macros/sidebar.html" import sidebar %}{% from
"macros/nav.html" import nav %} {% from "macros/js.html" import js%}

<!DOCTYPE html>
<html lang="en">
  {{ head()}}
  <body>
    {{ spinner()}}
    <div class="container-fluid position-relative d-flex p-0">
      {{ sidebar()}}

      <!-- Content Start -->
      <div class="content">
        {{ nav()}} {% block content%} {%endblock%}

        <!-- Footer Start -->
        <div class="container-fluid pt-4 px-4">
          <div class="bg-secondary rounded-top p-4">
            <div class="row">
              <div class="col-12 col-sm-6 text-center text-sm-start">
                &copy; <a href="#">Nurul Company</a>, All Right Reserved.
              </div>
              <div class="col-12 col-sm-6 text-center text-sm-end">
                <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                Designed By <a href="/">Nurul Sakinah</a> <br />Distributed By:
                <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
              </div>
            </div>
          </div>
        </div>
        <!-- Footer End -->
      </div>
      <!-- Content End -->
      <!-- Back to Top -->
      <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"
        ><i class="bi bi-arrow-up"></i
      ></a>
    </div>
    {{ js()}}
  </body>
</html>

templates/macros/nav.html
{% macro nav()%}<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
  <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
  </a>
  <a href="#" class="sidebar-toggler flex-shrink-0">
    <i class="fa fa-bars"></i>
  </a>
  <div class="navbar-nav align-items-center ms-auto">
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <img
          class="rounded-circle me-lg-2"
          src="img/user.jpg"
          alt=""
          style="width: 40px; height: 40px" />
        <span class="d-none d-lg-inline-flex"
          >{{ session.get('username')}}</span
        >
      </a>
      <div
        class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
        <a href="{{url_for('pages.logout')}}" class="dropdown-item">Log Out</a>
      </div>
    </div>
  </div>
</nav>
<!-- Navbar End -->{%endmacro%}

templates/macros/sidebar.html
{% macro sidebar()%}
<!-- Sidebar Start -->
<div class="sidebar pe-4 pb-3">
  <nav class="navbar bg-secondary navbar-dark">
    <a href="{{url_for('pages.index')}}" class="navbar-brand mx-4 mb-3">
      <h3 class="text-primary"><i class="fa fa-user-edit me-2"></i>Si-Kopi</h3>
    </a>
    <div class="d-flex align-items-center ms-4 mb-4">
      <div class="position-relative">
        <img
          class="rounded-circle"
          src="{{url_for('static', filename='img/user.jpg')}}"
          alt=""
          style="width: 40px; height: 40px" />
        <div
          class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
      </div>
      <div class="ms-3">
        <h6 class="mb-0">{{ session.get('username')}}</h6>
        <span>{{session.get('jabatan')}}</span>
      </div>
    </div>
    
    <div class="navbar-nav w-100">
      <a href="{{url_for('pages.index')}}"class="nav-item nav-link">
        <i class="fa fa-home me-2 parent-icon"></i>Dashboard
      </a>
      <a href="{{url_for('pages.barang')}}" class="nav-item nav-link"
        ><i class="fa fa-bookmark me-2"></i></i>Tabel Barang
      </a>
      <a href="{{url_for('pages.barang_masuk')}}" class="nav-item nav-link"
        ><i class="fa fa-laptop me-2"></i>Barang Masuk
      </a>
      <a href="{{url_for('pages.barang_out')}}" class="nav-item nav-link"
        ><i class="far fa-file-alt me-2"></i>Barang Keluar
      </a>
      <a href="{{url_for('pages.anggota')}}" class="nav-item nav-link"
        ><i class="far fa-user me-2"></i>Daftar Anggota
      </a>
      <a href="{{url_for('pages.pembayaran')}}" class="nav-item nav-link"
        ><i class="fa fa-chart-bar me-2"></i>Pembayaran
      </a>     
    </div>
  </nav>
</div>
<!-- Sidebar End -->
{%endmacro%}

templates/macros/spinner.html
{% macro spinner() %}
<!-- Spinner Start -->
<div
  id="spinner"
  class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
  <div
    class="spinner-border text-primary"
    style="width: 3rem; height: 3rem"
    role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
<!-- Spinner End -->
{% endmacro %}