routes.py
from flask import Blueprint, render_template, redirect, url_for, jsonify, session, flash
from sqlalchemy.exc import SQLAlchemyError
from passlib.handlers.pbkdf2 import pbkdf2_sha256

from form import AnggotaForm, BarangForm, BrgMasukForm, BrgOutForm, LoginForm
from models import AnggotaModel, BarangModel, BrgMasukModel, BrgOutModel, UserModel
from models import mysql

pages = Blueprint('pages', __name__, template_folder="templates", static_folder="static")

@pages.get('/')
@pages.route("/<_id>", methods=["GET", "POST"])
def index(_id=None):
    
    if session.get("id_user") is None:
        return redirect(url_for('.login'))
    
    getMsk = BrgMasukModel.get_all()
    getOut = BrgOutModel.get_all()
    
    total1 = sum(entry.qty for entry in getMsk)
    total2 = sum(entry.qty for entry in getOut)
    
    harga1 = sum(entry.harga_beli * entry.qty for entry in getMsk)
    harga2 = sum(entry.harga_jual * entry.qty for entry in getOut)
    
    return render_template( 'index.html',  side = 'Home', t1=total1, t2=total2, h1=harga1, h2=harga2 )

# login
@pages.route("/login", methods=['GET', 'POST'])
def login():
    if session.get("username"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = UserModel.get_user(form.username.data)

        if not user_data:
            flash("Login credentials not correct", category="error")
            return redirect(url_for(".login"))
    
        if user_data and pbkdf2_sha256.verify(form.password.data, user_data.password):
            session["id_user"] = user_data.id_user
            session["username"] = user_data.username
            session["jabatan"] = user_data.jabatan

            return redirect(url_for(".index"))

        flash("Login credentials not correct", "error")

    return render_template("login.html", form=form, side= 'Login' )


# logout
@pages.get("/logout")
def logout():
    session.clear()
    return redirect(url_for(".login"))


# regis
@pages.route("/registration", methods=["GET","POST"])
def reg():
    
    get_all_user = UserModel.get_all()
    form = LoginForm()
    
    if form.validate_on_submit():
        try:
            password = pbkdf2_sha256.encrypt(form.password.data)
            new_data = UserModel (form.username.data, form.password.data, form.jabatan.data)
            mysql.session.add(new_data)
            mysql.session.commit()
            
            return redirect(url_for('.login'))
        except SQLAlchemyError as ex:
            print(ex)
            mysql.session.rollback()
            
    return render_template("reg.html", form=form, data=get_all_user)



#  Fungsi untuk menampilkan Tabel Anggota
@pages.route("/anggota", methods=["GET","POST"])
def anggota():
    get_all_data = AnggotaModel.get_all()
    form = AnggotaForm()
    
    if form.validate_on_submit():
        if get_all_data:
            for i in get_all_data:
                if i.kode_anggota == form.kode_anggota.data:

                    return jsonify({'message': 'Kode Anggota Sudah Dipakai'}), 400        
        try:
            new_data = AnggotaModel(form.kode_anggota.data, form.nama_anggota.data, form.status.data, form.nik.data, form.bidang.data, form.keterangan.data)
            mysql.session.add(new_data)
            mysql.session.commit()
            
            return redirect(url_for('.anggota'))
        except SQLAlchemyError as ex:
            print(ex)
            mysql.session.rollback()
    
    return render_template("anggota.html", side = 'Anggota', form=form, data=get_all_data)


# Delete anggota
@pages.get("/anggota")
@pages.route("/anggota/<_id>", methods=['GET','POST'])
def deleteAnggota(_id=None):
    get_data_anggota = AnggotaModel.get_all()
    if _id is not None:
        deleteAnggota = AnggotaModel.get_by_id(_id)
        mysql.session.delete(deleteAnggota)
        mysql.session.commit()
        
        return redirect(url_for(".anggota"))

    return render_template("anggota.html", data=get_data_anggota)


# Edit Anggota
@pages.route('/anggota/edit/<_id>', methods=['GET', 'POST'] )
def editAnggota(_id):
    form = AnggotaForm()
    get_anggota_id = AnggotaModel.get_by_id(_id)
    if form.validate_on_submit():
        try:
            if form.kode_anggota.data != get_anggota_id.kode_anggota and form.kode_anggota.data is not None: get_anggota_id.kode_anggota = form.kode_anggota.data
            if form.nama_anggota.data != get_anggota_id.nama_anggota and form.nama_anggota.data is not None: get_anggota_id.nama_anggota = form.nama_anggota.data
            if form.status.data != get_anggota_id.status and form.status.data is not None: get_anggota_id.status = form.status.data
            if form.nik.data != get_anggota_id.nik and form.nik.data is not None: get_anggota_id.nik = form.nik.data
            if form.bidang.data != get_anggota_id.bidang and form.bidang.data is not None: get_anggota_id.bidang = form.bidang.data
            if form.keterangan.data != get_anggota_id.keterangan and form.keterangan.data is not None: get_anggota_id.keterangan = form.keterangan.data

            mysql.session.commit()
            
            return redirect(url_for('.anggota'))
        except SQLAlchemyError as x:
            print(x)
            mysql.session.rollback()
    return render_template("edit/edit-anggota.html", data=get_anggota_id, form=form)


# Tabel barang
@pages.route('/barang', methods=["GET","POST"])
def barang():
    get_all_data = BarangModel.get_all()
    form = BarangForm()
    
    if form.validate_on_submit():
        if get_all_data:
            try:
                new_data = BarangModel(form.nama_barang.data, form.satuan.data, form.harga_beli.data, form.harga_jual.data, form.stok_awal.data, form.keterangan.data)
                mysql.session.add(new_data)
                mysql.session.commit()
                
                return redirect(url_for('.barang'))
            except SQLAlchemyError as ex:
                print(ex)
                mysql.session.rollback()
            
    return render_template("barang.html", side="Barang", form=form, data=get_all_data)


# Edit barang
@pages.route('/barang/edit/<_id>', methods=['GET','POST'])
def editBarang(_id):
    get_barang_id = BarangModel.get_by_id(_id)
    form = BarangForm()
    
    if form.validate_on_submit():
        try:
            if form.nama_barang.data != get_barang_id.nama_barang and form.nama_barang.data is not None:
                get_barang_id.nama_barang = form.nama_barang.data
            if form.satuan.data != get_barang_id.satuan and form.satuan.data is not None:
                get_barang_id.satuan = form.satuan.data
            if form.harga_beli.data != get_barang_id.harga_beli and form.harga_beli.data is not None:
                get_barang_id.harga_beli = form.harga_beli.data
            if form.harga_jual.data != get_barang_id.harga_jual and form.harga_jual.data is not None:
                get_barang_id.harga_jual = form.harga_jual.data
            if form.stok_awal.data != get_barang_id.stok_awal and form.stok_awal.data is not None:
                get_barang_id.stok_awal = form.stok_awal.data
            if form.keterangan.data != get_barang_id.keterangan and form.keterangan.data is not None:
                get_barang_id.keterangan = form.keterangan.data

            mysql.session.commit()
            
            return redirect(url_for('.barang'))
        except SQLAlchemyError as x:
            print(x)
            mysql.session.rollback()
            
    return render_template("edit/edit-barang.html", side="Barang", form=form, data=get_barang_id)


# Delete barang
@pages.get("/barang")
@pages.route("/barang/<_id>", methods=['GET','POST'])
def deleteBarang(_id=None):
    get_data_barang = BarangModel.get_all()
    if _id is not None:
        deleteBarang = BarangModel.get_by_id(_id)
        mysql.session.delete(deleteBarang)
        mysql.session.commit()
        
        return redirect(url_for(".barang"))

    return render_template("barang.html", data=get_data_barang)


# tabel barang masuk
@pages.route("/barang/masuk", methods=["GET","POST"])
def barang_masuk():
    get_all_data = BrgMasukModel.get_all()
    form = BrgMasukForm()
    
    if form.validate_on_submit():
        if get_all_data:
            try:
                new_data = BrgMasukModel(form.tanggal_masuk.data, form.nama_barang.data, form.satuan.data, form.qty.data, form.harga_beli.data, form.distributor.data, form.keterangan.data)
                mysql.session.add(new_data)
                mysql.session.commit()
                
                return redirect(url_for('.barang_masuk'))
            except SQLAlchemyError as ex:
                print(ex)
                mysql.session.rollback()
                
    return render_template("barang-masuk.html", side ="Barang Masuk", data=get_all_data, form=form)


# edit brg masuk
@pages.route('/barang/masuk/edit/<_id>',methods=['GET','POST'] )  
def editBrgMasuk (_id):
    get_brgMasuk_id = BrgMasukModel.get_by_id(_id)
    form = BrgMasukForm()
    
    if form.validate_on_submit():
        try:
            if form.tanggal_masuk.data != get_brgMasuk_id.tanggal_masuk and form.tanggal_masuk.data is not None:
                get_brgMasuk_id.tanggal_masuk = form.tanggal_masuk.data
            if form.nama_barang.data != get_brgMasuk_id.nama_barang and form.nama_barang.data is not None:
                get_brgMasuk_id.nama_barang = form.nama_barang.data
            if form.satuan.data != get_brgMasuk_id.satuan and form.satuan.data is not None:
                get_brgMasuk_id.satuan = form.satuan.data
            if form.qty.data != get_brgMasuk_id.qty and form.qty.data is not None:

templates/anggota.html
{% extends "macros/main-layout.html" %} {% block content %}

<!-- Modal -->

<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-secondary">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Anggota</h1>
        <a
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"></a>
      </div>
      <form method="post" id="anggotaForm">
        {{ form.hidden_tag()}}
        <div class="modal-body">
          <div class="form-floating mb-3">
            {{form.kode_anggota(class="form-control", id="floatingInput")}}
            {{form.kode_anggota.label(class="form-label",for="floatingInput")}}
            
          </div>
          <div class="form-floating mb-3">
            {{form.nama_anggota(class="form-control", id="floating")}}
            {{form.nama_anggota.label(class="form-label",for="floating")}}
            
          </div>
          <div class="form-floating mb-3">
            {{form.status(class="form-control", id="floating")}}
            {{form.status.label(class="form-label",for="floating")}}
            
          </div>
          <div class="form-floating mb-3">
            {{form.nik(class="form-control", id="floating")}}
            {{form.nik.label(class="form-label",for="floating")}}
            
          </div>
          <div class="form-floating mb-3">
            {{form.bidang(class="form-control", id="floating")}}
            {{form.bidang.label(class="form-label",for="floating")}}
            
          </div>
          <div class="form-floating mb-3">
            {{form.keterangan(class="form-control", id="floating")}}
            {{form.keterangan.label(for="floating")}}
            
          </div>
        </div>
      

      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">
          Close
        </button>
        {{form.submit(class="btn btn-primary")}}
      </div>
    </div>
  </form>
  </div>
</div>

<div class="container-fluid pt-4 px-4">
  <button type="button" class="btn btn-primary rounded-pill m-2"  
  data-bs-toggle="modal"
  data-bs-target="#exampleModal">
    Tambah Anggota
  </button>
  <div class="col-12">
    <div class="bg-secondary rounded h-100 p-4">
      <h6 class="mb-4">Tabel Anggota</h6>

      <div class="table-responsive">
        <table class="table text-center" >
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">ID Anggota</th>
              <th scope="col">Nama Anggota</th>
              <th scope="col">Status</th>
              <th scope="col">NIP/NIK/NIS</th>
              <th scope="col">Bidang</th>
              <th scope="col">Keterangan</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            {%for i in data %}
            <tr>
              <th scope="row">{{loop.index}}</th>
              <td>{{ i.kode_anggota }}</td>
              <td>{{ i.nama_anggota }}</td>
              <td>{{ i.status }}</td>
              <td>{{ i.nik }}</td>
              <td>{{ i.bidang }}</td>
              <td>{{ i.keterangan }}</td>
              <td>
                <a href="{{ url_for('pages.editAnggota', _id=i.id) }}" class="btn btn-square btn-outline-success">
                  <i class="fa fa-pen">
                  </i>
                </a>
                <a href="{{ url_for('pages.deleteAnggota', _id=i.id) }}" class="btn btn-square btn-outline-primary m-2">
                  <i class="fa fa-eraser"></i>
                </a>

              </td>
              
            </tr>
            {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{%endblock%}

templates/barang.html
{%extends "macros/main-layout.html" %} {% block content%}

<!-- Modal -->

<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content bg-secondary">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Tambah Barang</h1>
        <a
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"></a>
      </div>
      <form method="post">
        {{ form.hidden_tag()}}
        <div class="modal-body">
          <div class="form-floating mb-3">
            {{ form.nama_barang(class="form-control", id="floatingInput") }}
            {{ form.nama_barang.label(class="form-label", for="floatingInput") }}
          </div>
          <div class="form-floating mb-3">
              {{ form.satuan(class="form-control", id="floating") }}
              {{ form.satuan.label(class="form-label", for="floating") }}
          </div>
          <div class="form-floating mb-3">
              {{ form.harga_beli(class="form-control", id="floating") }}
              {{ form.harga_beli.label(class="form-label", for="floating") }}
          </div>
          <div class="form-floating mb-3">
              {{ form.harga_jual(class="form-control", id="floating") }}
              {{ form.harga_jual.label(class="form-label", for="floating") }}
          </div>
          <div class="form-floating mb-3">
              {{ form.stok_awal(class="form-control", id="floating") }}
              {{ form.stok_awal.label(class="form-label", for="floating") }}
          </div>
          <div class="form-floating mb-3">
              {{ form.keterangan(class="form-control", id="floating") }}
              {{ form.keterangan.label(class="form-label", for="floating") }}
          </div>      
        </div>
      

      <div class="modal-footer">
        <button type="button" class="btn btn-info" data-bs-dismiss="modal">
          Close
        </button>
        {{form.submit(class="btn btn-primary")}}
      </div>
    </div>
  </form>
  </div>
</div>

<div class="container-fluid pt-4 px-4">
  <button type="button" class="btn btn-primary rounded-pill m-2 mb-3"  
  data-bs-toggle="modal"
  data-bs-target="#exampleModal">
    Tambah Barang
  </button>
  <div class="col-12">
    <div class="bg-secondary rounded h-100 p-4">
      <h6 class="mb-4">Responsive Table</h6>

      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nama Barang</th>
              <th scope="col">Satuan</th>
              <th scope="col">Harga Beli</th>
              <th scope="col">Harga Jual</th>
              <th scope="col">Stok Awal</th>
              <th scope="col">Keterangan</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
            {% for i in data %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ i.nama_barang }}</td>
                <td>{{ i.satuan }}</td>
                <td>{{ i.harga_beli }}</td>
                <td>{{ i.harga_jual }}</td>
                <td>{{ i.stok_awal }}</td>
                <td>{{ i.keterangan }}</td>
                <td>
                  <a href="{{ url_for('pages.editBarang', _id=i.id) }}" class="btn btn-square btn-outline-success">
                    <i class="fa fa-pen">
                    </i>
                  </a>
                  <a href="{{ url_for('pages.deleteBarang', _id=i.id) }}" class="btn btn-square btn-outline-primary m-2">
                    <i class="fa fa-eraser"></i>
                  </a>
  
                </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends "macros/main-layout.html" %} {% block content %}

<!-- Sale & Revenue Start -->
<div class="container-fluid pt-4 px-4">
  <div class="row g-4">
    <div class="col-sm-6 col-xl-3">
      <div
        class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-line fa-3x text-primary"></i>
        <div class="ms-3">
          <p class="mb-2">Persediaan</p>
          <h6 class="mb-0">{{t2}}</h6>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-xl-3">
      <div
        class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-bar fa-3x text-primary"></i>
        <div class="ms-3">
          <p class="mb-2">Total Sale</p>
          <h6 class="mb-0">Rp. {{"{:,.0f}".format(h2)}}</h6>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-xl-3">
      <div
        class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-area fa-3x text-primary"></i>
        <div class="ms-3">
          <p class="mb-2">Today Revenue</p>
          <h6 class="mb-0">{{t1}}</h6>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-xl-3">
      <div
        class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
        <i class="fa fa-chart-pie fa-3x text-primary"></i>
        <div class="ms-3">
          <p class="mb-2">Total Revenue</p>
          <h6 class="mb-0">Rp. {{"{:,.0f}".format(h1)}}</h6>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Sale & Revenue End -->

{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{{side}}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{{url_for('static', filename='img/favicon.ico')}}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
      rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link
      href="{{url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css')}}"
      rel="stylesheet" />
    <link
      href="{{url_for('static', filename='lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css')}}"
      rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
      rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link
      href="{{url_for('static', filename='css/style.css')}}"
      rel="stylesheet" />
  </head>

  <body>
    <div class="container-fluid position-relative d-flex p-0">
      <!-- Spinner Start -->
      <div
        id="spinner"
        class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div
          class="spinner-border text-primary"
          style="width: 3rem; height: 3rem"
          role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
      <!-- Spinner End -->

      <!-- Sign In Start -->
      <div class="container-fluid">
        <div
          class="row h-100 align-items-center justify-content-center"
          style="min-height: 100vh">
          <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="bg-secondary rounded p-4 p-sm-5 my-4 mx-3">
              <div
                class="d-flex align-items-center justify-content-between mb-3">
                <a href="index.html" class="">
                  <h3 class="text-primary">
                    <i class="fa fa-user-edit me-2"></i>Si-Kopi
                  </h3>
                </a>
                <h3>Sign In</h3>
              </div>
              <form method="post">
                {% with messages = get_flashed_messages(with_categories=True) %}
                {% for category, message in messages %} {% endfor %} {% endwith
                %} {{ form.hidden_tag() }}
                <div class="mb-3">
                  {{ form.username.label (class="form-label") }}
                  {{form.username(class="form-control") }}
                </div>
                <div class="mb-4">
                  {{ form.password.label (class="form-label") }}
                  {{form.password(class="form-control", type="password") }}
                </div>
                <div
                  class="d-flex align-items-center justify-content-between mb-4"></div>
                {{ form.submit(class="btn btn-primary py-3 w-100 mb-4") }}
                <p class="text-center mb-0">
                  Don't have an Account?
                  <a href="{{url_for('pages.reg')}}">Sign Up</a>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
      <!-- Sign In End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{url_for('static', filename='lib/chart/chart.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/easing/easing.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/waypoints/waypoints.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/owlcarousel/owl.carousel.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/tempusdominus/js/moment.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/tempusdominus/js/moment-timezone.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js')}}"></script>

    <!-- Template Javascript -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{{side}}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="" name="keywords" />
    <meta content="" name="description" />

    <!-- Favicon -->
    <link href="{{url_for('static', filename='img/favicon.ico')}}" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap"
      rel="stylesheet" />

    <!-- Icon Font Stylesheet -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
      rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css"
      rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link
      href="{{url_for('static', filename='lib/owlcarousel/assets/owl.carousel.min.css')}}"
      rel="stylesheet" />
    <link
      href="{{url_for('static', filename='lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css')}}"
      rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link
      href="{{url_for('static', filename='css/bootstrap.min.css')}}"
      rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link
      href="{{url_for('static', filename='css/style.css')}}"
      rel="stylesheet" />
  </head>

  <body>
    <div class="container-fluid position-relative d-flex p-0">
      <!-- Spinner Start -->
      <div
        id="spinner"
        class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div
          class="spinner-border text-primary"
          style="width: 3rem; height: 3rem"
          role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
      <!-- Spinner End -->

      <!-- Sign Up Start -->
      <div class="container-fluid">
        <div
          class="row h-100 align-items-center justify-content-center"
          style="min-height: 100vh">
          <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
            <div class="bg-secondary rounded p-4 p-sm-5 my-4 mx-3">
              <div
                class="d-flex align-items-center justify-content-between mb-3">
                <a href="index.html" class="">
                  <h3 class="text-primary">
                    <i class="fa fa-user-edit me-2"></i>Si-Kopi
                  </h3>
                </a>
                <h3>Sign Up</h3>
              </div>
              <form method="post">
                {{form.hidden_tag()}}
                <div class="mb-3">
                  {{ form.username.label (class="form-label") }}
                  {{form.username(class="form-control") }}
                </div>
                <div class="mb-3">
                  {{ form.jabatan.label (class="form-label") }}
                  {{form.jabatan(class="form-control") }}
                </div>
                <div class="mb-4">
                  {{ form.password.label (class="form-label") }}
                  {{form.password(class="form-control", type="password") }}
                </div>
                {{ form.submit(class="btn btn-primary py-3 w-100 mb-4") }}
              </form>
              <p class="text-center mb-0">
                Already have an Account?
                <a href="{{url_for('pages.login')}}">Sign In</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <!-- Sign Up End -->
    </div>
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{{url_for('static', filename='lib/chart/chart.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/easing/easing.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/waypoints/waypoints.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/owlcarousel/owl.carousel.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/tempusdominus/js/moment.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/tempusdominus/js/moment-timezone.min.js')}}"></script>
    <script src="{{url_for('static', filename='lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js')}}"></script>

    <!-- Template Javascript -->
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>